### PR TITLE
Retry logic for HTTP errors

### LINKED ISSUE #41: Add retry logic on HTTP errors
I got my first 502 gateway error from the CloudPassage SCA API today! If we end up losing a single report like that, for our purposes the combined report is incomplete and hence incorrect, so we need to start over from scratch.

But it's wasteful to have to throw all the fetched data away in order to try again. Ideally, we should add some retry logic on encountering an error, and only fail after trying some number of times.

### PR DESCRIPTION
**Pull request by ehashman**
Fixes #41.

WIP. Next steps:

- [x] Figure out what to do instead of passing the symbol "fail", probably throw an exception
- [x] Update `get-page!` to wrap `get-page-retry!` 
- [x] Remove the error handling inside various functions inside scans

### CODE REVIEW

File: src/cloudpassage_lib/scans.clj [hunk 1]
```diff
@@ -43,6 +43,17 @@
   [server-id module]
   (str (u/url base-servers-url server-id module)))
 
+(defn ^:private get-page-retry!
+  "Gets a page, and handles auth for you."
+  [token url num-tries]
+  (let [response (cpc/get-single-events-page! token url)]
+    (cond
+      (cpc/page-response-ok? response) response
+      (zero? num-tries) 'fail
```
Comment (derwolfe) [inline src/cloudpassage_lib/scans.clj]: Interesting! What is `'fail`? It seems like it is intended to be used as a keyword, but isn't a keyword. :-)

File: src/cloudpassage_lib/scans.clj [hunk 2]
```diff
@@ -43,6 +43,17 @@
   [server-id module]
   (str (u/url base-servers-url server-id module)))
 
+(defn ^:private get-page-retry!
+  "Gets a page, and handles auth for you."
+  [token url num-tries]
+  (let [response (cpc/get-single-events-page! token url)]
```
Comment (derwolfe) [inline src/cloudpassage_lib/scans.clj]: One issue that this might have is that `get-single-events-page!` returns a deferred. As such, this will not wait for the request to complete before iterating again. In order for this to work, the deferred returned by `get-single-events-page!` will need to be either unwrapped via a consuming function (see https://github.com/RackSec/cloudpassage-lib/blob/master/test/cloudpassage_lib/core_test.clj#L31 for an example) or dereferenced (using `@`).

File: test/cloudpassage_lib/scans_test.clj [hunk 3]
```diff
@@ -35,6 +52,25 @@
   (is (= "https://api.cloudpassage.com/v1/servers/server-id/svm"
          (#'scans/scan-server-url "server-id" "svm"))))
 
+(deftest get-page-retry!-tests
+  (testing "Returns 'fail after three tries"
+    (let [fake-get (constantly :cloudpassage-lib.core/fetch-error)]
```
Comment (derwolfe) [inline test/cloudpassage_lib/scans_test.clj]: Nice tests! The only issue I can see is that the tests handle the synchronous case where a deferred isn't involved. In order for this to function with `get-single-events-page!` (or any other deferred-returning function), this will need to handle unwrapping the value from the deferred. Here are a few examples of how to handle errors and success conditions (https://github.com/RackSec/cloudpassage-lib/blob/master/test/cloudpassage_lib/core_test.clj#L31)

File: src/cloudpassage_lib/scans.clj [hunk 4]
```diff
@@ -43,6 +43,21 @@
...
+   (cpc/get-single-events-page! token url)
+   (fn [response]
+     (cond
+       (cpc/page-response-ok? response) response
+       (zero? num-tries)
+       (do (error "No more retries.")
+           (throw (Exception. "Error fetching scans.")))
+       :else
+       (do (error "Couldn't fetch page. Retrying.")
+           (get-page-retry! token url (dec num-tries)))))))
```
Comment (ehashman) [inline src/cloudpassage_lib/scans.clj]: This is now an actual recursive call because recur binds to the lambda, which is not what we want. I'm not sure how problematic this is; since num-tries is going to be pretty small (3?), we're not really at risk of a stack overflow.

Unsure if there is a better way to do this.

Comment (derwolfe) [inline src/cloudpassage_lib/scans.clj]: To be honest, I'm not sure either. I feel like experimenting a bit :-).

File: test/cloudpassage_lib/scans_test.clj [hunk 5]
```diff
@@ -35,6 +52,34 @@
   (is (= "https://api.cloudpassage.com/v1/servers/server-id/svm"
          (#'scans/scan-server-url "server-id" "svm"))))
 
+(deftest get-page-retry!-tests
```
Comment (derwolfe) [inline test/cloudpassage_lib/scans_test.clj]: These are awesome.

File: src/cloudpassage_lib/scans.clj [hunk 6]
```diff
@@ -43,11 +43,26 @@
...
+   (cpc/get-single-events-page! token url)
+   (fn [response]
+     (cond
+       (cpc/page-response-ok? response) response
+       (zero? num-retries)
+       (do (error "No more retries.")
+           (throw (Exception. "Error fetching scans.")))
+       :else
+       (do (error "Couldn't fetch page. Retrying.")
+           (get-page-retry! token url (dec num-retries)))))))
```
Comment (derwolfe) [inline src/cloudpassage_lib/scans.clj]: My intuition is that `in` would wrap `get-page-retry...`.

File: src/cloudpassage_lib/scans.clj [hunk 7]
```diff
@@ -43,11 +44,28 @@
...
+   (fn [response]
+     (cond
+       (cpc/page-response-ok? response) response
+       (zero? num-retries)
+       (do (error "No more retries.")
+           (throw (Exception. "Error fetching scans.")))
+       :else
+       (do (error "Couldn't fetch page. Retrying.")
+           (mt/in
+            3000
```
Comment (derwolfe) [inline src/cloudpassage_lib/scans.clj]: What would you think of making this a parameter?

Comment (ehashman) [inline src/cloudpassage_lib/scans.clj]: Oh yeah, that seems eminently reasonable.

**Comment by derwolfe** [comment]
Nice work! This looks good to go :-)
